"""CommandGraph: intent-aware command discovery and command safety checks."""

__version__ = "0.1.0"

SEARCH_SCHEMA_VERSION = "commandgraph.search_result.v1"
RISK_SCHEMA_VERSION = "commandgraph.risk_review.v1"
REVIEW_SCHEMA_VERSION = "commandgraph.review.v1"
REVIEW_REQUEST_SCHEMA_VERSION = "commandgraph.review_request.v1"
ACTION_TRACE_SCHEMA_VERSION = "commandgraph.action_trace.v1"
RISK_RULES_SCHEMA_VERSION = "commandgraph.risk_rules.v1"
MAN_INDEX_SCHEMA_VERSION = "commandgraph.man_index.v1"
EFFECT_CATALOG_SCHEMA_VERSION = "commandgraph.effect_catalog.v1"
EFFECT_GRAPH_SCHEMA_VERSION = "commandgraph.effect_graph.v1"
PACK_MANIFEST_SCHEMA_VERSION = "commandgraph.command_pack.v1"
PACK_LIST_SCHEMA_VERSION = "commandgraph.pack_list.v1"
